### ISSUE TITLE
Strategy Info button in the Show Steps activity causes app to crash

### ISSUE THREAD

**Issue by CookieCrumbs19212** [yde773786/Solvadoku#8]
Pressing the info button next to each step in the Show Steps Activity which gives more information on a specific solving strategy causes the app to crash. 

Have not debugged it to find out what is causing the crash.

**Comment by yde773786** [comment]
Cannot recreate this issue, believe I've already fixed it earlier though.

**Comment by CookieCrumbs19212** [comment]
The issue only comes up in landscape mode. I'm guessing it's caused by the fact there isn't a dedicated check steps activity for the sw600dp qualifier.

**Comment by CookieCrumbs19212** [comment]
This issue has been resolved.
